- name: Configure tmux config
  synchronize:
    src: tmux/
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/"
    delete: true
    recursive: true 

- name: Find all Jinja2 template files in templates/tmux
  find:
    paths: "{{ role_path }}/templates/tmux"
    patterns: "*.j2"
    recurse: true
    file_type: file
  register: template_files

- name: Template all configuration files from templates/tmux
  loop: "{{ template_files.files }}"
  template:
    src: "{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/{{ item.path | regex_replace('^' + role_path + '/templates/tmux/', '') | regex_replace('.j2$', '') }}"

- name: Create symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/.config/tmux/tmux.conf"
    dest: "{{ ansible_facts['user_dir'] }}/.tmux.conf"
    state: link

- name: Find all scripts
  find:
    paths: "{{ ansible_facts['user_dir'] }}/.config/tmux"
    patterns: "*.sh"
    recurse: true
    file_type: file
  register: script_files

- name: Make scripts executable
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ script_files.files }}"
