ln -s ~/dotfiles/gypsum/.config/i3/config ~/.config/i3/config
ln -s ~/dotfiles/gypsum/.config/i3/polybar.sh ~/.config/i3/polybar.sh
ln -s ~/dotfiles/gypsum/.config/alacritty ~/.config/alacritty
ln -s ~/dotfiles/gypsum/.config/picom.conf ~/.config/picom.conf
ln -s ~/dotfiles/gypsum/.Xresources ~/.Xresources
ln -s ~/dotfiles/gypsum/.config/rofi ~/.config/rofi
ln -s ~/dotfiles/gypsum/.oh-my-zsh/custom/themes/haondt.zsh-theme ~/.oh-my-zsh/custom/themes/haondt.zsh-theme
ln -s ~/dotfiles/gypsum/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/gypsum/.config/nvim ~/.config/nvim
ln -s ~/dotfiles/gypsum/.zshrc ~/.zshrc
ln -s ~/dotfiles/gypsum/.config/polybar ~/.config/polybar
ln -s ~/dotfiles/gypsum/.tmux.conf ~/.tmux.conf
