---
- name: Set role defaults
  set_fact:
    azure: "{{ role_defaults | combine(azure | default({}), recursive=True) }}"

- name: Install Azure CLI
  become: true
  ansible.builtin.dnf:
    name: azure-cli
    state: present

- name: Configure Azure CLI
  include_role:
    name: azure-configure
