- name: Set role defaults
  set_fact:
    terraform: "{{ role_defaults | combine(terraform | default({}), recursive=True) }}"

- name: Check if Terraform is installed
  ansible.builtin.stat:
    path: /usr/bin/terraform
  register: terraform_bin

- name: Install Terraform
  when: not terraform_bin.stat.exists
  block:
    - name: Install HashiCorp repository
      become: true
      ansible.builtin.get_url:
        url: "{{ terraform.repo_url }}"
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: "0644"

    - name: Install Terraform
      become: true
      ansible.builtin.dnf:
        name: terraform
        state: present
