- name: Set role defaults
  set_fact:
    terraform: "{{ role_defaults | combine(terraform | default({}), recursive=True) }}"

- name: Check installed Terraform version
  ansible.builtin.command: /usr/bin/terraform version -json
  register: terraform_installed
  changed_when: false
  failed_when: false

- name: Parse installed version
  ansible.builtin.set_fact:
    terraform_current_version: >-
      {{ (terraform_installed.stdout | from_json).terraform_version
         if terraform_installed.rc == 0 else '' }}

- name: Install Terraform
  when: base.force or terraform_current_version != terraform.version
  block:
    - name: Install HashiCorp repository
      become: true
      ansible.builtin.get_url:
        url: "{{ terraform.repo_url }}"
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: "0644"

    - name: Install Terraform
      become: true
      ansible.builtin.dnf:
        name: "terraform-{{ terraform.version }}"
        state: present
        allow_downgrade: true
