- name: Ensure the bin directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.local/bin"
    state: directory

- name: Deploy scripts
  synchronize:
    src: scripts/
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/"
    delete: true
    recursive: true 

- name: Make scripts executable
  file:
    path: "{{ item }}"
    mode: '0755'
  with_fileglob:
    - "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/*.sh"
