- name: Set role defaults
  set_fact:
    base: "{{ role_defaults | combine(base, recursive=True) }}"

- name: Ensure home directories exist
  file:
    path: "{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: directory
  loop:
    - projects
    - files
    - downloads

- name: Ensure the bin directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.local/bin"
    state: directory

- name: Deploy scripts
  synchronize:
    src: scripts/
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/"
    delete: true
    recursive: true 

- name: Deploy additional scripts
  block:
    - name: Create user scripts directory
      file:
        path: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/user"
        state: directory
    - name: Deploy user scripts
      copy:
        content: "{{ item.value }}"
        dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/user/{{ item.key }}"
        mode: '0755'
      loop: "{{ base.scripts | dict2items }}"
  when: base.scripts | length > 0

- name: Find all scripts
  find:
    paths: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite"
    patterns: "*.sh"
    recurse: true
    file_type: file
  register: script_files

- name: Make scripts executable
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ script_files.files }}"

- name: Ensure the GTK3 Directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/gtk-3.0"
    state: directory

- name: Deploy GTK3 settings
  copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/gtk-3.0/settings.ini"
    content: |
      [Settings]
      gtk-application-prefer-dark-theme={{ 1 if base.scheme == 'dark' else 0 }}

- name: Ensure the GTK4 Directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/gtk-4.0"
    state: directory
- name: Deploy GTK4 settings
  copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/gtk-4.0/settings.ini"
    content: |
      [Settings]
      gtk-application-prefer-dark-theme={{ 1 if base.scheme == 'dark' else 0 }}

- name: Deploy user-dirs settings
  copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/user-dirs.dirs"
    content: |
      XDG_DOWNLOAD_DIR="$HOME/downloads"
      XDG_DOCUMENTS_DIR="$HOME/files"

