- name: Ensure the bin directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.local/bin"
    state: directory

- name: Deploy scripts
  synchronize:
    src: scripts/
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite/"
    delete: true
    recursive: true 

- name: Find all scripts
  find:
    paths: "{{ ansible_facts['user_dir'] }}/.local/bin/kunzite"
    patterns: "*.sh"
    recurse: true
    file_type: file
  register: script_files

- name: Make scripts executable
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ script_files.files }}"
