---
- name: Configure
  hosts: "{{ target_hosts }}"
  run_once: true
  vars:
    components_list: "{{ components | default('') | split(',') }}"
  tasks:
    - name: Base
      include_role:
        name: common
    - name: Configure component
      include_role:
        name: "{{ loop_component }}-configure"
      when: >-
        loop_component in always_configure_components or
        lookup('vars', loop_component, default={}).get('enabled', false)
      vars:
        always_configure_components:
          - k9s
          - azure
          - gcloud
      loop: "{{ components_list }}"
      loop_control:
        loop_var: loop_component
