---
- name: Install
  hosts: "{{ target_hosts }}"
  run_once: true
  roles:
    - role: common
    - role: base-configure
    - role: neovim
      when: neovim.enabled | bool
    - role: zsh
      when: zsh.enabled | bool
    - role: git
      when: git.enabled | bool
    - role: tmux
      when: tmux.enabled | bool
    - role: foot
      when: foot.enabled | bool
    - role: sway
      when: sway.enabled | bool
    - role: dev-tools
      when: dev_tools.enabled | bool
