---
- name: Configure
  hosts: "{{ target_hosts }}"
  run_once: true
  vars:
    components_list: "{{ components | default('') | split(',') }}"
  roles:
    - role: common
    - role: dev-tools
      when: "'dev-tools' in components_list and dev_tools.enabled | bool"
    - role: neovim
      when: "'neovim' in components_list and neovim.enabled | bool"
    - role: zsh
      when: "'zsh' in components_list and zsh.enabled | bool"
    - role: git
      when: "'git' in components_list and git.enabled | bool"
    - role: foot
      when: "'foot' in components_list and foot.enabled | bool"
    - role: sway
      when: "'sway' in components_list and sway.enabled | bool"
    - role: ly
      when: "'ly' in components_list and ly.enabled | bool"

    # Things that don't get called in the default "install all" playbook
    - role: storage
      when: "'storage' in components_list and storage.enabled | bool"
    - role: grub
      when: "'grub' in components_list and grub.enabled | bool"

    # Things that don't get called in the default "install all" playbook because they are included as dependencies
    - role: k9s
      when: "'k9s' in components_list"
