- name: Check if .gitconfig exists
  stat:
    path: "{{ ansible_facts['user_dir'] }}/.gitconfig"
  register: gitconfig_file

- name: Configure git
  when: not gitconfig_file.stat.exists
  include_role:
    name: git-configure
