common_role_defaults:
  base:
    enabled: true
    scheme: dark
    force: false
  neovim:
    enabled: false
  zsh:
    enabled: false
  git:
    enabled: false
  tmux:
    enabled: false
  foot:
    enabled: false
  sway:
    enabled: false
  dev_tools:
    enabled: false
    kubernetes:
      enabled: true
  storage:
    enabled: true
  grub:
    enabled: true
  ly:
    enabled: true
  sysctl:
    enabled: true
  k9s: {}
  go: {}
  colors:
    # special
    foreground: '#f3c6b1'
    #background: '#0b0708'
    background: '#3b272c'
    cursorColor: '#6e4952'

    black:
      dark: '#8e6c51'
      bright: '#b89f8b'
    red:
      dark: '#d44e45'
      bright: '#cc6666'
    green:
      dark: '#4f5040'
      bright: '#7daf69'
    yellow:
      dark: '#fcb685'
      bright: '#fcd1b3'
    blue:
      dark: '#c46692'
      bright: '#dfa0bd'
    magenta:
      dark: '#8d479e'
      bright: '#ad73be'
    cyan:
      dark: '#d98887'
      bright: '#f3afaf'
    white:
      dark: '#3e2d34'
      bright: '#eacfda'

