- name: Ensure the sway configuration directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/sway"
    state: directory
- name: Deploy sway config
  template:
    src: config.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/sway/config"
- name: Copy Sway Scripts
  synchronize:
    src: scripts/
    dest: "{{ ansible_facts['user_dir'] }}/.config/sway/scripts"
    delete: true
    recursive: true 
- name: Find all scripts
  find:
    paths: "{{ ansible_facts['user_dir'] }}/.config/sway/scripts"
    patterns: "*.sh"
    recurse: true
    file_type: file
  register: script_files
- name: Make scripts executable
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ script_files.files }}"

- name: Ensure the rofi configuration directory exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/rofi"
    state: directory
- name: Deploy rofi config
  template:
    src: rofi/config.rasi.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/rofi/config.rasi"
