- name: Set role defaults
  set_fact:
    git: "{{ role_defaults | combine(git, recursive=True) }}"

- name: Deploy .gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_facts['user_dir'] }}/.gitconfig"
