- name: Set role defaults
  set_fact:
    dev_tools: "{{ role_defaults | combine(dev_tools, recursive=True) }}"

- name: Install bun
  shell: curl -fsSL https://bun.com/install | bash
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.bun/bin/bun"

- name: Install dcdn
  shell: bun add -g https://gitlab.com/haondt/dcdn.git
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.bun/bin/dcdn"

- name: Set up .NET
  when: dev_tools.dotnet.enabled
  include_role:
    name: dotnet

- name: Install go
  when: dev_tools.go.enabled
  include_role:
    name: go

- name: Set up Kubernetes
  when: dev_tools.kubernetes.enabled
  block:
    - name: Install k9s
      include_role:
        name: k9s
    - name: Install packages
      become: true
      package:
        name:
          - kubernetes-client
          - helm


- name: Set up database tools
  block:
    - name: Install packages
      become: true
      package:
        name:
          - postgresql
    # required for lazygit
    - name: Install go
      include_role:
        name: go
    - name: Install lazysql via go install
      command: go install github.com/jorgerojas26/lazysql@latest
      args:
        creates: "{{ ansible_facts['user_dir'] }}/go/bin/lazysql"

- name: Set up chromium
  when: dev_tools.chromium.enabled
  become: true
  package:
    name: chromium

- name: Install docker
  when: dev_tools.docker.enabled
  block:
    - name: Install docker
      include_role:
        name: docker

